# BareMetal Common Build Configuration
# This file contains shared compiler flags, toolchain settings, and build options
# Include this in all Makefiles to ensure consistent build configuration

# Toolchain
CROSS_PREFIX := riscv64-unknown-elf-
CC = $(CROSS_PREFIX)gcc
CPP = $(CROSS_PREFIX)cpp
AR = $(CROSS_PREFIX)gcc-ar
OBJCOPY = $(CROSS_PREFIX)objcopy

# Architecture and ABI
AOPS = -march=rv64gc -mabi=lp64d -mcmodel=medany

# Compiler options
COPS = -Wall -Os -static -nostdlib -nostdinc -nostartfiles -ffreestanding -mstrict-align

# GCC include directory
GCC_INCLUDE = $(shell $(CC) -print-file-name=include)

# Quiet build output (set V=1 for verbose)
ifeq ($(V),1)
Q =
MSG = @true
else
Q = @
MSG = @echo
endif

# Determine SDK directory and project root from the location of this build.mk file
# $(lastword $(MAKEFILE_LIST)) gives us the path to this file (sdk/build.mk)
# $(dir ...) extracts the directory, $(abspath ...) makes it absolute
SDK_DIR = $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
PROJECT_ROOT = $(abspath $(SDK_DIR)/..)

# SDK absolute paths
SDK_YALIBC_INCLUDE = $(SDK_DIR)/yalibc/include
SDK_PLATFORM_INCLUDE = $(SDK_DIR)/platform/include
SDK_TARGETS_DIR = $(SDK_DIR)/targets

# Build directory (at project root)
BUILD_DIR = $(PROJECT_ROOT)/build

# Linker script directory (generated by SDK)
LDSCRIPT_DIR = $(BUILD_DIR)/ldscripts

# Base CFLAGS with SDK includes
CFLAGS = $(AOPS) $(COPS) 
CFLAGS += -I $(SDK_YALIBC_INCLUDE) -I $(SDK_PLATFORM_INCLUDE)
CFLAGS += -I $(GCC_INCLUDE)

# LTO settings - mandatory for all builds
# When debugging comment this out and uncomment the one below
CFLAGS += -flto=auto
#CFLAGS += -ffunction-sections -fdata-sections -g

# Linker options
LOPTS = -lgcc -Wl,--relax,--orphan-handling=warn,--no-dynamic-linker,--gc-sections,--print-gc-sections,--strip-discarded

# Helper function to generate platform library linking flags for LTO
# Usage: $(call PLATFORM_LIB,target)
# Example: $(call PLATFORM_LIB,qemu) expands to: -Wl,--whole-archive $(BUILD_DIR)/libplatform_qemu.a -Wl,--no-whole-archive
# Required for proper LTO linking - ensures all object files and LTO metadata are available to the linker
define PLATFORM_LIB
-Wl,--whole-archive $(BUILD_DIR)/libplatform_$(1).a -Wl,--no-whole-archive
endef

# Objcopy options
CPOPS = -O binary --gap-fill=0
